/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_ricardoquiroz;

/**
 *
 * @author rjqer
 */
public class Examen2P2_Main extends javax.swing.JFrame {

    /**
     * Creates new form Examen2P2_Main
     */
    public Examen2P2_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_crudempleados = new javax.swing.JDialog();
        JD_crudcarros = new javax.swing.JDialog();
        JD_otrosmenus = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        JB_crudempleados = new javax.swing.JButton();
        JB_crudcarros = new javax.swing.JButton();
        JB_otrosmenus = new javax.swing.JButton();

        javax.swing.GroupLayout JD_crudempleadosLayout = new javax.swing.GroupLayout(JD_crudempleados.getContentPane());
        JD_crudempleados.getContentPane().setLayout(JD_crudempleadosLayout);
        JD_crudempleadosLayout.setHorizontalGroup(
            JD_crudempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_crudempleadosLayout.setVerticalGroup(
            JD_crudempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_crudcarrosLayout = new javax.swing.GroupLayout(JD_crudcarros.getContentPane());
        JD_crudcarros.getContentPane().setLayout(JD_crudcarrosLayout);
        JD_crudcarrosLayout.setHorizontalGroup(
            JD_crudcarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_crudcarrosLayout.setVerticalGroup(
            JD_crudcarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_otrosmenusLayout = new javax.swing.GroupLayout(JD_otrosmenus.getContentPane());
        JD_otrosmenus.getContentPane().setLayout(JD_otrosmenusLayout);
        JD_otrosmenusLayout.setHorizontalGroup(
            JD_otrosmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_otrosmenusLayout.setVerticalGroup(
            JD_otrosmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema del Taller");

        JB_crudempleados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JB_crudempleados.setText("Ingresar CRUD Empleados");

        JB_crudcarros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JB_crudcarros.setText("Ingresar CRUD Carros");

        JB_otrosmenus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JB_otrosmenus.setText("Simulacion/Pagos/Entregas/Reparaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_crudcarros, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_crudempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(JB_otrosmenus)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(JB_crudempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_crudcarros, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_otrosmenus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2P2_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_crudcarros;
    private javax.swing.JButton JB_crudempleados;
    private javax.swing.JButton JB_otrosmenus;
    private javax.swing.JDialog JD_crudcarros;
    private javax.swing.JDialog JD_crudempleados;
    private javax.swing.JDialog JD_otrosmenus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
