/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_ricardoquiroz;

/**
 *
 * @author rjqer
 */
public class Examen2P2_Main extends javax.swing.JFrame {

    /**
     * Creates new form Examen2P2_Main
     */
    public Examen2P2_Main() {
        initComponents();
    }
    
    public void showCrudempleados(){
        JD_crudempleados.setModal(true);
        JD_crudempleados.pack();;
        JD_crudempleados.setLocationRelativeTo(this);
        JD_crudempleados.setVisible(true);
    }
    
    public void showCrudcarros(){
        JD_crudcarros.setModal(true);
        JD_crudcarros.pack();;
        JD_crudcarros.setLocationRelativeTo(this);
        JD_crudcarros.setVisible(true);
    }
    
    public void showOtrosmenus(){
        JD_otrosmenus.setModal(true);
        JD_otrosmenus.pack();;
        JD_otrosmenus.setLocationRelativeTo(this);
        JD_otrosmenus.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_crudempleados = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JP_crearempleado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TF_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JS_edad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JS_carrosrep = new javax.swing.JSpinner();
        JB_crearempleado = new javax.swing.JButton();
        JP_eliminarempleado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JD_crudcarros = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        JP_crearcarro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TF_marca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_modelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JS_anofab = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        JR_espera = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        JS_costorep = new javax.swing.JSpinner();
        JB_crearcarro = new javax.swing.JButton();
        JP_modificarcarro = new javax.swing.JPanel();
        JP_listarcarro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JD_otrosmenus = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        JP_simulacion = new javax.swing.JPanel();
        JC_simempleados = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JC_simcarros = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        JPB_barrarep = new javax.swing.JProgressBar();
        JB_simular = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA_estadofinal = new javax.swing.JTextArea();
        JP_pagos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable_pagos = new javax.swing.JTable();
        JP_entregas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JP_reparaciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_reparaciones = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        JP_bgframe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JB_crudempleados = new javax.swing.JButton();
        JB_crudcarros = new javax.swing.JButton();
        JB_otrosmenus = new javax.swing.JButton();

        JP_crearempleado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nombre:");

        TF_nombre.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setText("Edad:");

        jLabel7.setText("ID:");

        TF_id.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setText("Carros Reparados:");

        JB_crearempleado.setBackground(new java.awt.Color(204, 255, 255));
        JB_crearempleado.setText("Crear Empleado");

        javax.swing.GroupLayout JP_crearempleadoLayout = new javax.swing.GroupLayout(JP_crearempleado);
        JP_crearempleado.setLayout(JP_crearempleadoLayout);
        JP_crearempleadoLayout.setHorizontalGroup(
            JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_crearempleadoLayout.createSequentialGroup()
                .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_crearempleadoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TF_nombre)
                                .addComponent(JS_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TF_id, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                            .addComponent(JS_carrosrep, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JP_crearempleadoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(JB_crearempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(720, Short.MAX_VALUE))
        );
        JP_crearempleadoLayout.setVerticalGroup(
            JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_crearempleadoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JS_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_crearempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JS_carrosrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(JB_crearempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creacion", JP_crearempleado);

        JP_eliminarempleado.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JP_eliminarempleadoLayout = new javax.swing.GroupLayout(JP_eliminarempleado);
        JP_eliminarempleado.setLayout(JP_eliminarempleadoLayout);
        JP_eliminarempleadoLayout.setHorizontalGroup(
            JP_eliminarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        JP_eliminarempleadoLayout.setVerticalGroup(
            JP_eliminarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminacion", JP_eliminarempleado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("CRUD Empleados");

        javax.swing.GroupLayout JD_crudempleadosLayout = new javax.swing.GroupLayout(JD_crudempleados.getContentPane());
        JD_crudempleados.getContentPane().setLayout(JD_crudempleadosLayout);
        JD_crudempleadosLayout.setHorizontalGroup(
            JD_crudempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JD_crudempleadosLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_crudempleadosLayout.setVerticalGroup(
            JD_crudempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_crudempleadosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JP_crearcarro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Marca:");

        TF_marca.setBackground(new java.awt.Color(204, 255, 255));

        jLabel10.setText("Modelo:");

        TF_modelo.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setText("Año Fabriacado:");

        jLabel12.setText("Estado:");

        buttonGroup1.add(JR_espera);
        JR_espera.setSelected(true);
        JR_espera.setText("EsperaEntrarReparacion");

        jLabel13.setText("Costo Reparacion:");

        JB_crearcarro.setBackground(new java.awt.Color(204, 255, 255));
        JB_crearcarro.setText("Crear Carro");

        javax.swing.GroupLayout JP_crearcarroLayout = new javax.swing.GroupLayout(JP_crearcarro);
        JP_crearcarro.setLayout(JP_crearcarroLayout);
        JP_crearcarroLayout.setHorizontalGroup(
            JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_crearcarroLayout.createSequentialGroup()
                .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_crearcarroLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(TF_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JP_crearcarroLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TF_modelo)
                                .addComponent(JS_anofab, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(JR_espera)
                                .addComponent(JS_costorep))))
                    .addGroup(JP_crearcarroLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(JB_crearcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(703, Short.MAX_VALUE))
        );
        JP_crearcarroLayout.setVerticalGroup(
            JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_crearcarroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TF_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JS_anofab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JR_espera))
                .addGap(18, 18, 18)
                .addGroup(JP_crearcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JS_costorep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(JB_crearcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Creacion", JP_crearcarro);

        JP_modificarcarro.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JP_modificarcarroLayout = new javax.swing.GroupLayout(JP_modificarcarro);
        JP_modificarcarro.setLayout(JP_modificarcarroLayout);
        JP_modificarcarroLayout.setHorizontalGroup(
            JP_modificarcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1063, Short.MAX_VALUE)
        );
        JP_modificarcarroLayout.setVerticalGroup(
            JP_modificarcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Modificacion", JP_modificarcarro);

        JP_listarcarro.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JP_listarcarroLayout = new javax.swing.GroupLayout(JP_listarcarro);
        JP_listarcarro.setLayout(JP_listarcarroLayout);
        JP_listarcarroLayout.setHorizontalGroup(
            JP_listarcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1063, Short.MAX_VALUE)
        );
        JP_listarcarroLayout.setVerticalGroup(
            JP_listarcarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Listar", JP_listarcarro);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("CRUD Carros");

        javax.swing.GroupLayout JD_crudcarrosLayout = new javax.swing.GroupLayout(JD_crudcarros.getContentPane());
        JD_crudcarros.getContentPane().setLayout(JD_crudcarrosLayout);
        JD_crudcarrosLayout.setHorizontalGroup(
            JD_crudcarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JD_crudcarrosLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_crudcarrosLayout.setVerticalGroup(
            JD_crudcarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_crudcarrosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JP_simulacion.setBackground(new java.awt.Color(255, 255, 255));

        JC_simempleados.setBackground(new java.awt.Color(204, 255, 255));
        JC_simempleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sdasd" }));

        jLabel14.setText("Empleados:");

        jLabel15.setText("Carros:");

        JC_simcarros.setBackground(new java.awt.Color(204, 255, 255));
        JC_simcarros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", " ", " " }));

        jLabel16.setText("Reparacion del Vehiculo:");

        JPB_barrarep.setForeground(new java.awt.Color(51, 255, 0));
        JPB_barrarep.setStringPainted(true);

        JB_simular.setBackground(new java.awt.Color(204, 255, 255));
        JB_simular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JB_simular.setText("Simular");

        jLabel17.setText("Estado Final del Vehicullo:");

        TA_estadofinal.setBackground(new java.awt.Color(204, 255, 255));
        TA_estadofinal.setColumns(20);
        TA_estadofinal.setRows(5);
        jScrollPane2.setViewportView(TA_estadofinal);

        javax.swing.GroupLayout JP_simulacionLayout = new javax.swing.GroupLayout(JP_simulacion);
        JP_simulacion.setLayout(JP_simulacionLayout);
        JP_simulacionLayout.setHorizontalGroup(
            JP_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_simulacionLayout.createSequentialGroup()
                .addGroup(JP_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_simulacionLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(JP_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPB_barrarep, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(JP_simulacionLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(JC_simempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JC_simcarros, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JP_simulacionLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(JB_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286)
                        .addComponent(jLabel17)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        JP_simulacionLayout.setVerticalGroup(
            JP_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_simulacionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(JP_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JC_simempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(JC_simcarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(JPB_barrarep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(JP_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Simulacion", JP_simulacion);

        JP_pagos.setBackground(new java.awt.Color(255, 255, 255));

        JTable_pagos.setBackground(new java.awt.Color(204, 255, 255));
        JTable_pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carro", "Pago Completado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JTable_pagos);

        javax.swing.GroupLayout JP_pagosLayout = new javax.swing.GroupLayout(JP_pagos);
        JP_pagos.setLayout(JP_pagosLayout);
        JP_pagosLayout.setHorizontalGroup(
            JP_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_pagosLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        JP_pagosLayout.setVerticalGroup(
            JP_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_pagosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pagos", JP_pagos);

        JP_entregas.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carro", "Estado Entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout JP_entregasLayout = new javax.swing.GroupLayout(JP_entregas);
        JP_entregas.setLayout(JP_entregasLayout);
        JP_entregasLayout.setHorizontalGroup(
            JP_entregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_entregasLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        JP_entregasLayout.setVerticalGroup(
            JP_entregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_entregasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Entregas", JP_entregas);

        JP_reparaciones.setBackground(new java.awt.Color(255, 255, 255));

        JTable_reparaciones.setBackground(new java.awt.Color(204, 255, 255));
        JTable_reparaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empleado", "Carro a Reparar", "Exito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_reparaciones);

        javax.swing.GroupLayout JP_reparacionesLayout = new javax.swing.GroupLayout(JP_reparaciones);
        JP_reparaciones.setLayout(JP_reparacionesLayout);
        JP_reparacionesLayout.setHorizontalGroup(
            JP_reparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_reparacionesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        JP_reparacionesLayout.setVerticalGroup(
            JP_reparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_reparacionesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Reparaciones", JP_reparaciones);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Sistema del Taller");

        javax.swing.GroupLayout JD_otrosmenusLayout = new javax.swing.GroupLayout(JD_otrosmenus.getContentPane());
        JD_otrosmenus.getContentPane().setLayout(JD_otrosmenusLayout);
        JD_otrosmenusLayout.setHorizontalGroup(
            JD_otrosmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JD_otrosmenusLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_otrosmenusLayout.setVerticalGroup(
            JD_otrosmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_otrosmenusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        JP_bgframe.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema del Taller");

        JB_crudempleados.setBackground(new java.awt.Color(204, 255, 255));
        JB_crudempleados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JB_crudempleados.setText("Ingresar CRUD Empleados");
        JB_crudempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_crudempleadosMouseClicked(evt);
            }
        });

        JB_crudcarros.setBackground(new java.awt.Color(204, 255, 255));
        JB_crudcarros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JB_crudcarros.setText("Ingresar CRUD Carros");
        JB_crudcarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_crudcarrosMouseClicked(evt);
            }
        });

        JB_otrosmenus.setBackground(new java.awt.Color(204, 255, 255));
        JB_otrosmenus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JB_otrosmenus.setText("Simulacion/Pagos/Entregas/Reparaciones");
        JB_otrosmenus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_otrosmenusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JP_bgframeLayout = new javax.swing.GroupLayout(JP_bgframe);
        JP_bgframe.setLayout(JP_bgframeLayout);
        JP_bgframeLayout.setHorizontalGroup(
            JP_bgframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_bgframeLayout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
            .addGroup(JP_bgframeLayout.createSequentialGroup()
                .addGroup(JP_bgframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_bgframeLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(JP_bgframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JB_crudcarros, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_crudempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JP_bgframeLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(JB_otrosmenus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_bgframeLayout.setVerticalGroup(
            JP_bgframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_bgframeLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(JB_crudempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_crudcarros, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_otrosmenus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_bgframe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_bgframe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_crudempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_crudempleadosMouseClicked
        // TODO add your handling code here:
        showCrudempleados();
    }//GEN-LAST:event_JB_crudempleadosMouseClicked

    private void JB_crudcarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_crudcarrosMouseClicked
        // TODO add your handling code here:
        showCrudcarros();
    }//GEN-LAST:event_JB_crudcarrosMouseClicked

    private void JB_otrosmenusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_otrosmenusMouseClicked
        // TODO add your handling code here:
        showOtrosmenus();
    }//GEN-LAST:event_JB_otrosmenusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2P2_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_crearcarro;
    private javax.swing.JButton JB_crearempleado;
    private javax.swing.JButton JB_crudcarros;
    private javax.swing.JButton JB_crudempleados;
    private javax.swing.JButton JB_otrosmenus;
    private javax.swing.JButton JB_simular;
    private javax.swing.JComboBox<String> JC_simcarros;
    private javax.swing.JComboBox<String> JC_simempleados;
    private javax.swing.JDialog JD_crudcarros;
    private javax.swing.JDialog JD_crudempleados;
    private javax.swing.JDialog JD_otrosmenus;
    private javax.swing.JProgressBar JPB_barrarep;
    private javax.swing.JPanel JP_bgframe;
    private javax.swing.JPanel JP_crearcarro;
    private javax.swing.JPanel JP_crearempleado;
    private javax.swing.JPanel JP_eliminarempleado;
    private javax.swing.JPanel JP_entregas;
    private javax.swing.JPanel JP_listarcarro;
    private javax.swing.JPanel JP_modificarcarro;
    private javax.swing.JPanel JP_pagos;
    private javax.swing.JPanel JP_reparaciones;
    private javax.swing.JPanel JP_simulacion;
    private javax.swing.JRadioButton JR_espera;
    private javax.swing.JSpinner JS_anofab;
    private javax.swing.JSpinner JS_carrosrep;
    private javax.swing.JSpinner JS_costorep;
    private javax.swing.JSpinner JS_edad;
    private javax.swing.JTable JTable_pagos;
    private javax.swing.JTable JTable_reparaciones;
    private javax.swing.JTextArea TA_estadofinal;
    private javax.swing.JTextField TF_id;
    private javax.swing.JTextField TF_marca;
    private javax.swing.JTextField TF_modelo;
    private javax.swing.JTextField TF_nombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
